fly-on-message: '&8[&2Hyvox&8] &bOra puoi volare come un uccellino :3!'

fly-off-message: '&8[&2Hyvox&8] &cSei diventato improvvisamente pesante.'

god-on-message: '&8[&2Hyvox&8] &bFigo, ora sei come teo e L3RTON (ma non herisson), Goditi questa GodMode'

god-off-message: '&8[&2Hyvox&8] &cSei tornato a essere te stesso, &lChe Schifo.'
